-- Esta é uma solução apenas para teste. 
-- Não deve ser usada em Produção!!

Create database Carros

go
use Carros
go

DROP TABLE IF EXISTS FORNECEDOR

CREATE TABLE FORNECEDOR (
	CODIGO_FORNECEDOR INT,
	NOME_FORNECEDOR VARCHAR(255),
    CIDADE VARCHAR(255),
)
GO

INSERT INTO FORNECEDOR VALUES(1,'Superpeças','VITORIA')
INSERT INTO FORNECEDOR VALUES(2,'Peçauto','VITORIA')
INSERT INTO FORNECEDOR VALUES(3,'transportMinas','BH')
GO

DROP TABLE IF EXISTS PECA

CREATE TABLE PECA (
	CODIGO_PEÇA VARCHAR(255),
    NOME_PEÇA VARCHAR(255),
    PRECO INT,
)
GO

INSERT INTO PECA VALUES('MOTOR','PECA MOTOR',1000)
INSERT INTO PECA VALUES('CAPO','PECA CAPO',100)
GO

DROP TABLE IF EXISTS CARRO

CREATE TABLE CARRO (
	CODIGO_CARRO VARCHAR(255)
)
GO

INSERT INTO CARRO VALUES('KOMBI')
INSERT INTO CARRO VALUES('GOL')
GO

DROP TABLE IF EXISTS FORNECIMENTO

CREATE TABLE FORNECIMENTO (
	CODIGO_FORNECEDOR INT,
    CODIGO_PECA VARCHAR(255),
	CODIGO_CARRO VARCHAR(255)
)
GO

INSERT INTO FORNECIMENTO VALUES(1,'MOTOR','KOMBI')
INSERT INTO FORNECIMENTO VALUES(2,'MOTOR','KOMBI')
INSERT INTO FORNECIMENTO VALUES(3,'MOTOR','GOL')
INSERT INTO FORNECIMENTO VALUES(4,'CAPO','GOL')
GO

SELECT * FROM FORNECIMENTO
GO
SELECT * FROM CARRO
GO
SELECT * FROM PECA
GO
SELECT * FROM FORNECEDOR
GO